
x = input("My name is RudeAI. I would like to ask you a few questions. Press enter.")
name = input("What is your name?")
print("Your name is " , name , "?!! Why would anyone name you that?")
print("")
age = input("How old are you " + name + "?")
print("You're " + age + "? You're getting up there!")
print("")
fun = input("So what do you do for fun " + name + "? ")
print("Hah! Only nerds " + fun + "?")
print("")
music = input("What kind of music do you listen to?")
print("Wowwww!!! " + music + " is trash. " + music + " is the worst type of music!!")
print("")
siblings = input("How many siblings do you have " + name + "?")
print(siblings + "? Wowww, I bet you're the ugliest one out of them!!")
print("")
job = input("What do you want to be when you grow up " + name + "?")
print("Don't you have to be smarter to be a " + job + "?!! So " + name + ", you're " + age + "... You like to " + fun + " and listen to " + music + ". Good luck being a " + job + ". I'm not kidding. I really despise you " + name + ".")
